tailscaled: tailscaled --tun=userspace-networking --statedir /config/tailscale
tailscale: /tailscale.sh 
caddy: caddy run -c /etc/caddy/Caddyfile
rclone: /await.sh caddy && /rclone.sh
jellyfin: /await.sh rclone && /jellyfin/jellyfin
